version: '3.2'

services:
  node-red:
    build: .
    ports:
      - "1880:1880"
    volumes:
      - ./data:/data
      - ./public:/public
      #- ./node-red/:/usr/src/node-red
  mongo:
    ports:
      - "27017:27017"      

